<?php

// 由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '新手剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 5,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铁剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 15,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '精钢剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 30,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '符文剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 50,
            'crit_rate' => 0.05,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '龙牙剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 80,
            'crit_damage' => 0.3,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '泰坦之剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 120,
            'max_hp' => 100,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 160,
            'max_hp' => 150,
            'defense' => 30,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '狂战士之剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 220,
            'strength' => 25,
            'crit_damage' => 0.5,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使之剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 300,
            'max_hp' => 300,
            'crit_rate' => 0.15,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神圣审判剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 400,
            'all_stats' => 15,
            'crit_damage' => 0.8,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王之剑',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 550,
            'max_hp' => 800,
            'crit_rate' => 0.2,
            'crit_damage' => 1,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒之刃',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 700,
            'all_stats' => 30,
            'crit_damage' => 1.2,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌斩裂者',
        'type' => 'weapon',
        'sub_type' => 'sword',
        'base_stats' => [
            'attack' => 900,
            'max_hp' => 1500,
            'crit_rate' => 0.25,
            'crit_damage' => 1.5,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '新手法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 3,
            'max_mana' => 20,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '橡木法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 10,
            'max_mana' => 50,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '水晶法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 25,
            'max_mana' => 100,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '月亮法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 45,
            'max_mana' => 200,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '星辰法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 70,
            'max_mana' => 350,
            'crit_rate' => 0.08,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '虚空法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 100,
            'max_mana' => 500,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '奥术法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 140,
            'energy' => 20,
            'max_mana' => 700,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '凤凰法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 200,
            'max_mana' => 1000,
            'crit_damage' => 0.4,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 280,
            'max_mana' => 1500,
            'crit_rate' => 0.12,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '大魔导师法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 380,
            'energy' => 40,
            'max_mana' => 2200,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之启示法杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 500,
            'max_mana' => 3000,
            'all_stats' => 20,
            'crit_rate' => 0.18,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒魔力源',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 650,
            'max_mana' => 4000,
            'crit_damage' => 1,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌魔杖',
        'type' => 'weapon',
        'sub_type' => 'staff',
        'base_stats' => [
            'attack' => 850,
            'energy' => 60,
            'max_mana' => 5500,
            'crit_rate' => 0.22,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '新手弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 4,
            'crit_rate' => 0.02,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '长弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 12,
            'crit_rate' => 0.05,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '精灵弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 28,
            'crit_rate' => 0.1,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '猎魔弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 48,
            'crit_rate' => 0.15,
            'crit_damage' => 0.25,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '暗影之弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 75,
            'crit_rate' => 0.2,
            'dexterity' => 15,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '风神之弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 110,
            'crit_rate' => 0.25,
            'crit_damage' => 0.5,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '精灵王之弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 150,
            'crit_rate' => 0.28,
            'dexterity' => 25,
            'crit_damage' => 0.6,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '凤凰羽弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 210,
            'crit_rate' => 0.32,
            'crit_damage' => 0.8,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使之弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 290,
            'crit_rate' => 0.35,
            'dexterity' => 40,
            'crit_damage' => 1,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神射手之弓',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 390,
            'crit_rate' => 0.4,
            'crit_damage' => 1.2,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之狩猎者',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 520,
            'all_stats' => 20,
            'crit_rate' => 0.45,
            'crit_damage' => 1.5,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒追猎者',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 680,
            'crit_rate' => 0.5,
            'crit_damage' => 1.8,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌穿刺者',
        'type' => 'weapon',
        'sub_type' => 'bow',
        'base_stats' => [
            'attack' => 880,
            'crit_rate' => 0.55,
            'dexterity' => 80,
            'crit_damage' => 2.2,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '布帽',
        'type' => 'helmet',
        'sub_type' => 'cloth',
        'base_stats' => [
            'max_hp' => 10,
            'defense' => 2,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '皮帽',
        'type' => 'helmet',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 20,
            'defense' => 5,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铁盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 50,
            'defense' => 15,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '秘银头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 80,
            'defense' => 5,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '龙骨头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 150,
            'defense' => 40,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神圣头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 250,
            'defense' => 60,
            'max_mana' => 50,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 400,
            'defense' => 90,
            'vitality' => 20,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 600,
            'defense' => 130,
            'all_stats' => 10,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 900,
            'defense' => 180,
            'vitality' => 40,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 1300,
            'defense' => 250,
            'all_stats' => 20,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 2000,
            'defense' => 350,
            'vitality' => 60,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 3000,
            'defense' => 480,
            'all_stats' => 35,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王头盔',
        'type' => 'helmet',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 4500,
            'defense' => 650,
            'vitality' => 100,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '布衣',
        'type' => 'armor',
        'sub_type' => 'cloth',
        'base_stats' => [
            'max_hp' => 20,
            'defense' => 5,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '皮甲',
        'type' => 'armor',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 40,
            'defense' => 12,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '锁子甲',
        'type' => 'armor',
        'sub_type' => 'mail',
        'base_stats' => [
            'max_hp' => 80,
            'defense' => 25,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '板甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 120,
            'defense' => 40,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '秘银甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 200,
            'defense' => 65,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '龙鳞甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 20,
            'max_hp' => 350,
            'defense' => 100,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 500,
            'defense' => 20,
        ],
        'required_level' => 30,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 800,
            'defense' => 220,
            'vitality' => 30,
        ],
        'required_level' => 40,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 1200,
            'defense' => 300,
            'all_stats' => 15,
        ],
        'required_level' => 50,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神圣铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 1800,
            'defense' => 400,
            'vitality' => 50,
        ],
        'required_level' => 60,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 2600,
            'defense' => 550,
            'all_stats' => 25,
        ],
        'required_level' => 70,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 4000,
            'defense' => 750,
            'vitality' => 80,
        ],
        'required_level' => 80,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 6000,
            'defense' => 1000,
            'all_stats' => 40,
        ],
        'required_level' => 90,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王铠甲',
        'type' => 'armor',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 9000,
            'defense' => 200,
            'vitality' => 120,
        ],
        'required_level' => 100,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '布手套',
        'type' => 'gloves',
        'sub_type' => 'cloth',
        'base_stats' => [
            'defense' => 1,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '皮手套',
        'type' => 'gloves',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 3,
            'crit_rate' => 0.02,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铁手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 3,
            'defense' => 8,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '精钢手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 8,
            'defense' => 15,
            'crit_rate' => 0.03,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '龙皮手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 15,
            'defense' => 25,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '力量手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 30,
            'strength' => 10,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 40,
            'defense' => 40,
            'strength' => 15,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 60,
            'all_stats' => 10,
            'crit_rate' => 0.1,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 90,
            'defense' => 60,
            'crit_damage' => 0.4,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 130,
            'all_stats' => 20,
            'crit_rate' => 0.15,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 180,
            'strength' => 50,
            'crit_damage' => 0.6,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 250,
            'all_stats' => 35,
            'crit_rate' => 0.2,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王手套',
        'type' => 'gloves',
        'sub_type' => 'plate',
        'base_stats' => [
            'attack' => 350,
            'strength' => 80,
            'crit_damage' => 1,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '布鞋',
        'type' => 'boots',
        'sub_type' => 'cloth',
        'base_stats' => [
            'defense' => 1,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '皮靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 3,
            'dexterity' => 2,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铁靴',
        'type' => 'boots',
        'sub_type' => 'plate',
        'base_stats' => [
            'defense' => 8,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '迅捷之靴',
        'type' => 'boots',
        'sub_type' => 'plate',
        'base_stats' => [
            'defense' => 12,
            'crit_rate' => 0.05,
            'dexterity' => 8,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '游侠之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 20,
            'dexterity' => 15,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '幻影之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 30,
            'dexterity' => 25,
            'crit_damage' => 0.15,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士靴',
        'type' => 'boots',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 150,
            'defense' => 45,
            'dexterity' => 30,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 35,
            'crit_rate' => 0.12,
            'dexterity' => 45,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神速之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 50,
            'dexterity' => 65,
            'crit_damage' => 0.3,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 70,
            'crit_rate' => 0.18,
            'dexterity' => 90,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 100,
            'dexterity' => 120,
            'crit_damage' => 0.5,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 140,
            'crit_rate' => 0.25,
            'dexterity' => 160,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王之靴',
        'type' => 'boots',
        'sub_type' => 'leather',
        'base_stats' => [
            'defense' => 200,
            'all_stats' => 30,
            'dexterity' => 220,
            'crit_damage' => 0.8,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '布腰带',
        'type' => 'belt',
        'sub_type' => 'cloth',
        'base_stats' => [
            'max_hp' => 10,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '皮带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 25,
            'defense' => 2,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铁腰带',
        'type' => 'belt',
        'sub_type' => 'plate',
        'base_stats' => [
            'max_hp' => 50,
            'defense' => 5,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '巨人腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 100,
            'vitality' => 10,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '生命腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 200,
            'vitality' => 20,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '泰坦腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 350,
            'strength' => 15,
            'vitality' => 35,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 550,
            'defense' => 30,
            'vitality' => 45,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 850,
            'vitality' => 60,
            'all_stats' => 10,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 1200,
            'strength' => 40,
            'vitality' => 80,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 1700,
            'vitality' => 100,
            'all_stats' => 20,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 2500,
            'strength' => 60,
            'vitality' => 130,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 3500,
            'vitality' => 170,
            'all_stats' => 35,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王腰带',
        'type' => 'belt',
        'sub_type' => 'leather',
        'base_stats' => [
            'max_hp' => 5000,
            'strength' => 100,
            'vitality' => 220,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '铜戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 2,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '银戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 5,
            'crit_rate' => 0.02,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '金戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 10,
            'crit_rate' => 0.05,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '红宝石戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 15,
            'crit_damage' => 0.2,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '蓝宝石戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 12,
            'max_mana' => 100,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '翡翠戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 100,
            'defense' => 10,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '乌鸦戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 25,
            'crit_rate' => 0.1,
            'crit_damage' => 0.3,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '乔丹之石',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 30,
            'max_mana' => 150,
            'all_stats' => 5,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '矮人戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 200,
            'defense' => 30,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '魔法戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'energy' => 20,
            'max_mana' => 300,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 45,
            'defense' => 25,
            'all_stats' => 10,
        ],
        'required_level' => 35,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使之戒',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 65,
            'max_hp' => 300,
            'crit_rate' => 0.12,
        ],
        'required_level' => 45,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神之戒指',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 90,
            'all_stats' => 15,
            'crit_damage' => 0.5,
        ],
        'required_level' => 55,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒之戒',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 120,
            'crit_rate' => 0.18,
            'crit_damage' => 0.6,
        ],
        'required_level' => 65,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌之戒',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 160,
            'max_hp' => 600,
            'all_stats' => 25,
        ],
        'required_level' => 75,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世之戒',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 220,
            'crit_rate' => 0.22,
            'crit_damage' => 0.8,
        ],
        'required_level' => 85,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王之戒',
        'type' => 'ring',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 300,
            'all_stats' => 40,
            'crit_damage' => 1,
        ],
        'required_level' => 95,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '木制护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 15,
        ],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '骨制护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 30,
            'max_mana' => 15,
        ],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '水晶护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 50,
            'defense' => 5,
            'max_mana' => 50,
        ],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '狮子护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 20,
            'max_hp' => 80,
            'defense' => 15,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '猫眼护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'crit_rate' => 0.15,
            'dexterity' => 15,
            'crit_damage' => 0.3,
        ],
        'required_level' => 15,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => 'marshal护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 100,
            'max_mana' => 100,
            'all_stats' => 10,
        ],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '地狱护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 40,
            'strength' => 20,
            'crit_damage' => 0.5,
        ],
        'required_level' => 25,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神圣护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 300,
            'max_mana' => 300,
            'all_stats' => 20,
        ],
        'required_level' => 30,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '圣骑士护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 60,
            'max_hp' => 400,
            'defense' => 40,
        ],
        'required_level' => 40,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '天使护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 500,
            'max_mana' => 500,
            'all_stats' => 25,
        ],
        'required_level' => 50,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神圣天使护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 100,
            'all_stats' => 30,
            'crit_damage' => 0.6,
        ],
        'required_level' => 60,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '永恒护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 1000,
            'max_mana' => 1000,
            'all_stats' => 35,
        ],
        'required_level' => 70,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '混沌护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 180,
            'crit_rate' => 0.2,
            'crit_damage' => 0.8,
        ],
        'required_level' => 80,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '创世护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'max_hp' => 2000,
            'max_mana' => 2000,
            'all_stats' => 50,
        ],
        'required_level' => 90,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    [
        'name' => '神王护符',
        'type' => 'amulet',
        'sub_type' => NULL,
        'base_stats' => [
            'attack' => 300,
            'all_stats' => 60,
            'crit_damage' => 1.2,
        ],
        'required_level' => 100,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
    ],
    // 药品（商店固定显示，按等级显示最高可用档位）
    [
        'name' => '轻型生命药水',
        'type' => 'potion',
        'sub_type' => 'hp',
        'base_stats' => ['max_hp' => 10, 'price' => 5],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 50],
    ],
    [ 
        'name' => '生命药水',
        'type' => 'potion',
        'sub_type' => 'hp',
        'base_stats' => ['max_hp' => 50, 'price' => 25],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 100],
    ],
    [
        'name' => '强效生命药水',
        'type' => 'potion',
        'sub_type' => 'hp',
        'base_stats' => ['max_hp' => 100, 'price' => 50],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 200],
    ],
    [
        'name' => '超级生命药水',
        'type' => 'potion',
        'sub_type' => 'hp',
        'base_stats' => ['max_hp' => 200, 'price' => 100],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 400],
    ],
    [
        'name' => '轻型法力药水',
        'type' => 'potion',
        'sub_type' => 'mp',
        'base_stats' => ['max_mana' => 10, 'price' => 5],
        'required_level' => 1,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 30],
    ],
    [
        'name' => '法力药水',
        'type' => 'potion',
        'sub_type' => 'mp',
        'base_stats' => ['max_mana' => 50, 'price' => 25],
        'required_level' => 5,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 60],
    ],
    [
        'name' => '强效法力药水',
        'type' => 'potion',
        'sub_type' => 'mp',
        'base_stats' => ['max_mana' => 100, 'price' => 50],
        'required_level' => 10,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 120],
    ],
    [
        'name' => '超级法力药水',
        'type' => 'potion',
        'sub_type' => 'mp',
        'base_stats' => ['max_mana' => 200, 'price' => 100],
        'required_level' => 20,
        'required_strength' => 0,
        'required_dexterity' => 0,
        'required_energy' => 0,
        'sockets' => 0,
        'gem_stats' => ['restore' => 240],
    ],
];
