<?php

return [
    [
        'name' => '小野猪',
        'type' => 'normal',
        'level' => 1,
        'hp_base' => 30,
        'hp_per_level' => 8,
        'attack_base' => 3,
        'attack_per_level' => 2,
        'defense_base' => 1,
        'defense_per_level' => 1,
        'experience_base' => 10,
        'experience_per_level' => 5,
        ],
    [
        'name' => '野狼',
        'type' => 'normal',
        'level' => 2,
        'hp_base' => 40,
        'hp_per_level' => 10,
        'attack_base' => 5,
        'attack_per_level' => 2,
        'defense_base' => 2,
        'defense_per_level' => 1,
        'experience_base' => 15,
        'experience_per_level' => 6,
        ],
    [
        'name' => '森林哥布林',
        'type' => 'normal',
        'level' => 3,
        'hp_base' => 70,
        'hp_per_level' => 15,
        'attack_base' => 10,
        'attack_per_level' => 3,
        'defense_base' => 4,
        'defense_per_level' => 1,
        'experience_base' => 20,
        'experience_per_level' => 8,
        ],
    [
        'name' => '巨狼',
        'type' => 'elite',
        'level' => 5,
        'hp_base' => 150,
        'hp_per_level' => 30,
        'attack_base' => 15,
        'attack_per_level' => 4,
        'defense_base' => 6,
        'defense_per_level' => 2,
        'experience_base' => 50,
        'experience_per_level' => 15,
        ],
    [
        'name' => '树人长老',
        'type' => 'boss',
        'level' => 8,
        'hp_base' => 400,
        'hp_per_level' => 80,
        'attack_base' => 25,
        'attack_per_level' => 6,
        'defense_base' => 12,
        'defense_per_level' => 3,
        'experience_base' => 150,
        'experience_per_level' => 40,
        ],
    [
        'name' => '野猪王',
        'type' => 'elite',
        'level' => 6,
        'hp_base' => 200,
        'hp_per_level' => 40,
        'attack_base' => 20,
        'attack_per_level' => 5,
        'defense_base' => 8,
        'defense_per_level' => 2,
        'experience_base' => 70,
        'experience_per_level' => 20,
        ],
    [
        'name' => '蝙蝠',
        'type' => 'normal',
        'level' => 5,
        'hp_base' => 45,
        'hp_per_level' => 10,
        'attack_base' => 12,
        'attack_per_level' => 3,
        'defense_base' => 3,
        'defense_per_level' => 1,
        'experience_base' => 25,
        'experience_per_level' => 8,
        ],
    [
        'name' => '洞穴蜘蛛',
        'type' => 'normal',
        'level' => 6,
        'hp_base' => 55,
        'hp_per_level' => 12,
        'attack_base' => 14,
        'attack_per_level' => 3,
        'defense_base' => 4,
        'defense_per_level' => 1,
        'experience_base' => 30,
        'experience_per_level' => 10,
        ],
    [
        'name' => '骷髅兵',
        'type' => 'normal',
        'level' => 7,
        'hp_base' => 80,
        'hp_per_level' => 18,
        'attack_base' => 16,
        'attack_per_level' => 4,
        'defense_base' => 8,
        'defense_per_level' => 2,
        'experience_base' => 40,
        'experience_per_level' => 12,
        ],
    [
        'name' => '骷髅法师',
        'type' => 'elite',
        'level' => 10,
        'hp_base' => 200,
        'hp_per_level' => 40,
        'attack_base' => 25,
        'attack_per_level' => 5,
        'defense_base' => 10,
        'defense_per_level' => 3,
        'experience_base' => 80,
        'experience_per_level' => 20,
        ],
    [
        'name' => '骸骨之王',
        'type' => 'boss',
        'level' => 12,
        'hp_base' => 600,
        'hp_per_level' => 100,
        'attack_base' => 35,
        'attack_per_level' => 8,
        'defense_base' => 18,
        'defense_per_level' => 4,
        'experience_base' => 250,
        'experience_per_level' => 60,
        ],
    [
        'name' => '巨型蜘蛛',
        'type' => 'elite',
        'level' => 8,
        'hp_base' => 180,
        'hp_per_level' => 35,
        'attack_base' => 22,
        'attack_per_level' => 5,
        'defense_base' => 9,
        'defense_per_level' => 2,
        'experience_base' => 65,
        'experience_per_level' => 18,
        ],
    [
        'name' => '小恶魔',
        'type' => 'normal',
        'level' => 12,
        'hp_base' => 100,
        'hp_per_level' => 25,
        'attack_base' => 25,
        'attack_per_level' => 5,
        'defense_base' => 10,
        'defense_per_level' => 2,
        'experience_base' => 60,
        'experience_per_level' => 15,
        ],
    [
        'name' => '火焰元素',
        'type' => 'normal',
        'level' => 14,
        'hp_base' => 120,
        'hp_per_level' => 30,
        'attack_base' => 30,
        'attack_per_level' => 6,
        'defense_base' => 12,
        'defense_per_level' => 3,
        'experience_base' => 80,
        'experience_per_level' => 20,
        ],
    [
        'name' => '地狱骑士',
        'type' => 'elite',
        'level' => 16,
        'hp_base' => 350,
        'hp_per_level' => 70,
        'attack_base' => 40,
        'attack_per_level' => 8,
        'defense_base' => 20,
        'defense_per_level' => 4,
        'experience_base' => 150,
        'experience_per_level' => 35,
        ],
    [
        'name' => '地狱魔王',
        'type' => 'boss',
        'level' => 20,
        'hp_base' => 1000,
        'hp_per_level' => 200,
        'attack_base' => 60,
        'attack_per_level' => 12,
        'defense_base' => 30,
        'defense_per_level' => 6,
        'experience_base' => 500,
        'experience_per_level' => 100,
        ],
    [
        'name' => '炎魔',
        'type' => 'elite',
        'level' => 18,
        'hp_base' => 400,
        'hp_per_level' => 80,
        'attack_base' => 50,
        'attack_per_level' => 10,
        'defense_base' => 22,
        'defense_per_level' => 5,
        'experience_base' => 180,
        'experience_per_level' => 40,
        ],
    [
        'name' => '恶魔巫师',
        'type' => 'elite',
        'level' => 19,
        'hp_base' => 320,
        'hp_per_level' => 65,
        'attack_base' => 55,
        'attack_per_level' => 11,
        'defense_base' => 15,
        'defense_per_level' => 4,
        'experience_base' => 160,
        'experience_per_level' => 38,
        ],
    [
        'name' => '深渊魔虫',
        'type' => 'normal',
        'level' => 22,
        'hp_base' => 180,
        'hp_per_level' => 40,
        'attack_base' => 55,
        'attack_per_level' => 11,
        'defense_base' => 25,
        'defense_per_level' => 5,
        'experience_base' => 150,
        'experience_per_level' => 35,
        ],
    [
        'name' => '暗影幽灵',
        'type' => 'normal',
        'level' => 24,
        'hp_base' => 200,
        'hp_per_level' => 45,
        'attack_base' => 60,
        'attack_per_level' => 12,
        'defense_base' => 20,
        'defense_per_level' => 4,
        'experience_base' => 180,
        'experience_per_level' => 40,
        ],
    [
        'name' => '虚空行者',
        'type' => 'elite',
        'level' => 26,
        'hp_base' => 600,
        'hp_per_level' => 120,
        'attack_base' => 80,
        'attack_per_level' => 16,
        'defense_base' => 35,
        'defense_per_level' => 7,
        'experience_base' => 300,
        'experience_per_level' => 70,
        ],
    [
        'name' => '深渊领主',
        'type' => 'boss',
        'level' => 30,
        'hp_base' => 2000,
        'hp_per_level' => 400,
        'attack_base' => 120,
        'attack_per_level' => 24,
        'defense_base' => 60,
        'defense_per_level' => 12,
        'experience_base' => 1000,
        'experience_per_level' => 200,
        ],
    [
        'name' => '天使卫士',
        'type' => 'normal',
        'level' => 32,
        'hp_base' => 300,
        'hp_per_level' => 60,
        'attack_base' => 90,
        'attack_per_level' => 18,
        'defense_base' => 45,
        'defense_per_level' => 9,
        'experience_base' => 300,
        'experience_per_level' => 70,
        ],
    [
        'name' => '炽天使',
        'type' => 'normal',
        'level' => 35,
        'hp_base' => 350,
        'hp_per_level' => 70,
        'attack_base' => 100,
        'attack_per_level' => 20,
        'defense_base' => 50,
        'defense_per_level' => 10,
        'experience_base' => 350,
        'experience_per_level' => 80,
        ],
    [
        'name' => '天使长',
        'type' => 'elite',
        'level' => 38,
        'hp_base' => 900,
        'hp_per_level' => 180,
        'attack_base' => 130,
        'attack_per_level' => 26,
        'defense_base' => 70,
        'defense_per_level' => 14,
        'experience_base' => 600,
        'experience_per_level' => 140,
        ],
    [
        'name' => '堕落天使',
        'type' => 'elite',
        'level' => 42,
        'hp_base' => 1100,
        'hp_per_level' => 220,
        'attack_base' => 150,
        'attack_per_level' => 30,
        'defense_base' => 80,
        'defense_per_level' => 16,
        'experience_base' => 750,
        'experience_per_level' => 170,
        ],
    [
        'name' => '大天使长',
        'type' => 'boss',
        'level' => 45,
        'hp_base' => 3500,
        'hp_per_level' => 700,
        'attack_base' => 200,
        'attack_per_level' => 40,
        'defense_base' => 100,
        'defense_per_level' => 20,
        'experience_base' => 2000,
        'experience_per_level' => 400,
        ],
    [
        'name' => '圣殿骑士',
        'type' => 'elite',
        'level' => 40,
        'hp_base' => 1000,
        'hp_per_level' => 200,
        'attack_base' => 140,
        'attack_per_level' => 28,
        'defense_base' => 90,
        'defense_per_level' => 18,
        'experience_base' => 680,
        'experience_per_level' => 155,
        ],
    [
        'name' => '神仆',
        'type' => 'normal',
        'level' => 48,
        'hp_base' => 500,
        'hp_per_level' => 100,
        'attack_base' => 160,
        'attack_per_level' => 32,
        'defense_base' => 80,
        'defense_per_level' => 16,
        'experience_base' => 500,
        'experience_per_level' => 110,
        ],
    [
        'name' => '神使',
        'type' => 'normal',
        'level' => 52,
        'hp_base' => 600,
        'hp_per_level' => 120,
        'attack_base' => 180,
        'attack_per_level' => 36,
        'defense_base' => 90,
        'defense_per_level' => 18,
        'experience_base' => 600,
        'experience_per_level' => 130,
        ],
    [
        'name' => '神将',
        'type' => 'elite',
        'level' => 55,
        'hp_base' => 1500,
        'hp_per_level' => 300,
        'attack_base' => 220,
        'attack_per_level' => 44,
        'defense_base' => 120,
        'defense_per_level' => 24,
        'experience_base' => 1000,
        'experience_per_level' => 220,
        ],
    [
        'name' => '神官',
        'type' => 'elite',
        'level' => 58,
        'hp_base' => 1300,
        'hp_per_level' => 260,
        'attack_base' => 240,
        'attack_per_level' => 48,
        'defense_base' => 100,
        'defense_per_level' => 20,
        'experience_base' => 1100,
        'experience_per_level' => 240,
        ],
    [
        'name' => '神王化身',
        'type' => 'boss',
        'level' => 60,
        'hp_base' => 5000,
        'hp_per_level' => 1000,
        'attack_base' => 300,
        'attack_per_level' => 60,
        'defense_base' => 150,
        'defense_per_level' => 30,
        'experience_base' => 3500,
        'experience_per_level' => 700,
        ],
    [
        'name' => '审判天使',
        'type' => 'elite',
        'level' => 62,
        'hp_base' => 1800,
        'hp_per_level' => 360,
        'attack_base' => 280,
        'attack_per_level' => 56,
        'defense_base' => 140,
        'defense_per_level' => 28,
        'experience_base' => 1300,
        'experience_per_level' => 280,
        ],
    [
        'name' => '永恒守护者',
        'type' => 'normal',
        'level' => 65,
        'hp_base' => 800,
        'hp_per_level' => 160,
        'attack_base' => 260,
        'attack_per_level' => 52,
        'defense_base' => 130,
        'defense_per_level' => 26,
        'experience_base' => 800,
        'experience_per_level' => 170,
        ],
    [
        'name' => '时空裂隙',
        'type' => 'normal',
        'level' => 70,
        'hp_base' => 1000,
        'hp_per_level' => 200,
        'attack_base' => 300,
        'attack_per_level' => 60,
        'defense_base' => 150,
        'defense_per_level' => 30,
        'experience_base' => 1000,
        'experience_per_level' => 210,
        ],
    [
        'name' => '永恒战士',
        'type' => 'elite',
        'level' => 72,
        'hp_base' => 2500,
        'hp_per_level' => 500,
        'attack_base' => 380,
        'attack_per_level' => 76,
        'defense_base' => 200,
        'defense_per_level' => 40,
        'experience_base' => 1800,
        'experience_per_level' => 380,
        ],
    [
        'name' => '永恒法师',
        'type' => 'elite',
        'level' => 75,
        'hp_base' => 2200,
        'hp_per_level' => 440,
        'attack_base' => 420,
        'attack_per_level' => 84,
        'defense_base' => 180,
        'defense_per_level' => 36,
        'experience_base' => 2000,
        'experience_per_level' => 420,
        ],
    [
        'name' => '永恒之王',
        'type' => 'boss',
        'level' => 78,
        'hp_base' => 8000,
        'hp_per_level' => 1600,
        'attack_base' => 500,
        'attack_per_level' => 100,
        'defense_base' => 250,
        'defense_per_level' => 50,
        'experience_base' => 6000,
        'experience_per_level' => 1200,
        ],
    [
        'name' => '永恒骑士',
        'type' => 'elite',
        'level' => 80,
        'hp_base' => 3000,
        'hp_per_level' => 600,
        'attack_base' => 450,
        'attack_per_level' => 90,
        'defense_base' => 230,
        'defense_per_level' => 46,
        'experience_base' => 2400,
        'experience_per_level' => 500,
        ],
    [
        'name' => '混沌精灵',
        'type' => 'normal',
        'level' => 82,
        'hp_base' => 1400,
        'hp_per_level' => 280,
        'attack_base' => 400,
        'attack_per_level' => 80,
        'defense_base' => 200,
        'defense_per_level' => 40,
        'experience_base' => 1400,
        'experience_per_level' => 290,
        ],
    [
        'name' => '虚空领主',
        'type' => 'normal',
        'level' => 85,
        'hp_base' => 1800,
        'hp_per_level' => 360,
        'attack_base' => 450,
        'attack_per_level' => 90,
        'defense_base' => 220,
        'defense_per_level' => 44,
        'experience_base' => 1800,
        'experience_per_level' => 370,
        ],
    [
        'name' => '混沌战士',
        'type' => 'elite',
        'level' => 88,
        'hp_base' => 4000,
        'hp_per_level' => 800,
        'attack_base' => 550,
        'attack_per_level' => 110,
        'defense_base' => 280,
        'defense_per_level' => 56,
        'experience_base' => 3200,
        'experience_per_level' => 650,
        ],
    [
        'name' => '混沌魔神',
        'type' => 'elite',
        'level' => 92,
        'hp_base' => 5000,
        'hp_per_level' => 1000,
        'attack_base' => 650,
        'attack_per_level' => 130,
        'defense_base' => 320,
        'defense_per_level' => 64,
        'experience_base' => 4000,
        'experience_per_level' => 800,
        ],
    [
        'name' => '混沌之源',
        'type' => 'boss',
        'level' => 96,
        'hp_base' => 15000,
        'hp_per_level' => 3000,
        'attack_base' => 800,
        'attack_per_level' => 160,
        'defense_base' => 400,
        'defense_per_level' => 80,
        'experience_base' => 10000,
        'experience_per_level' => 2000,
        ],
    [
        'name' => '混沌之王',
        'type' => 'boss',
        'level' => 100,
        'hp_base' => 25000,
        'hp_per_level' => 5000,
        'attack_base' => 1000,
        'attack_per_level' => 200,
        'defense_base' => 500,
        'defense_per_level' => 100,
        'experience_base' => 20000,
        'experience_per_level' => 4000,
        ],
];
