<?php

// 由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '重击',
        'type' => 'active',
        'class_restriction' => 'warrior',
        'mana_cost' => 10,
        'cooldown' => 3,
        'effects' => [],
        'description' => '强力一击，造成额外伤害',
    ],
    [
        'name' => '战吼',
        'type' => 'active',
        'class_restriction' => 'warrior',
        'mana_cost' => 15,
        'cooldown' => 10,
        'effects' => [
            'duration' => 5,
            'buff_attack' => 10,
        ],
        'description' => '发出怒吼，提升攻击力',
    ],
    [
        'name' => '铁壁',
        'type' => 'passive',
        'class_restriction' => 'warrior',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'defense_bonus' => 5,
        ],
        'description' => '被动提升防御力',
    ],
    [
        'name' => '旋风斩',
        'type' => 'active',
        'class_restriction' => 'warrior',
        'mana_cost' => 25,
        'cooldown' => 6,
        'effects' => [],
        'description' => '旋转攻击周围所有敌人',
    ],
    [
        'name' => '狂暴',
        'type' => 'active',
        'class_restriction' => 'warrior',
        'mana_cost' => 40,
        'cooldown' => 30,
        'effects' => [
            'duration' => 10,
            'buff_attack' => 50,
        ],
        'description' => '进入狂暴状态，大幅提升攻击力',
    ],
    [
        'name' => '钢铁之躯',
        'type' => 'passive',
        'class_restriction' => 'warrior',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'hp_bonus' => 100,
            'defense_bonus' => 10,
        ],
        'description' => '被动提升生命值和防御力',
    ],
    [
        'name' => '斩杀',
        'type' => 'active',
        'class_restriction' => 'warrior',
        'mana_cost' => 30,
        'cooldown' => 8,
        'effects' => [
            'execute_threshold' => 0.3,
            'execute_multiplier' => 2,
        ],
        'description' => '对低血量敌人造成巨额伤害',
    ],
    [
        'name' => '火球术',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 2,
        'effects' => [],
        'description' => '发射火球，造成魔法伤害',
    ],
    [
        'name' => '冰霜新星',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 5,
        'effects' => [],
        'description' => '释放冰霜，造成范围伤害',
    ],
    [
        'name' => '魔力涌动',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'mana_bonus' => 20,
        ],
        'description' => '被动提升法力上限',
    ],
    [
        'name' => '雷击',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 25,
        'cooldown' => 4,
        'effects' => [],
        'description' => '召唤闪电，瞬间造成高额伤害',
    ],
    [
        'name' => '魔法护盾',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 35,
        'cooldown' => 15,
        'effects' => [
            'shield' => 100,
            'duration' => 8,
        ],
        'description' => '用法力值吸收伤害',
    ],
    [
        'name' => '奥术智慧',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'spell_power_bonus' => 15,
        ],
        'description' => '被动提升魔法攻击力',
    ],
    [
        'name' => '陨石术',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 12,
        'effects' => [],
        'description' => '召唤陨石从天而降',
    ],
    [
        'name' => '法力燃烧',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 6,
        'effects' => [
            'mana_burn' => 50,
        ],
        'description' => '燃烧敌人法力并造成伤害',
    ],
    [
        'name' => '穿刺射击',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 12,
        'cooldown' => 2,
        'effects' => [
            'crit_bonus' => 0.2,
        ],
        'description' => '精准射击，高暴击',
    ],
    [
        'name' => '多重射击',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 18,
        'cooldown' => 4,
        'effects' => [],
        'description' => '同时射出多支箭',
    ],
    [
        'name' => '鹰眼',
        'type' => 'passive',
        'class_restriction' => 'ranger',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'crit_rate_bonus' => 0.03,
        ],
        'description' => '被动提升暴击率',
    ],
    [
        'name' => '毒箭',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 15,
        'cooldown' => 5,
        'effects' => [
            'dot' => 15,
            'dot_duration' => 5,
        ],
        'description' => '射出毒箭，持续造成伤害',
    ],
    [
        'name' => '闪避',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 20,
        'cooldown' => 12,
        'effects' => [
            'duration' => 6,
            'dodge_bonus' => 0.3,
        ],
        'description' => '提升闪避率',
    ],
    [
        'name' => '致命瞄准',
        'type' => 'passive',
        'class_restriction' => 'ranger',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'crit_damage_bonus' => 0.15,
        ],
        'description' => '被动提升暴击伤害',
    ],
    [
        'name' => '箭雨',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 45,
        'cooldown' => 10,
        'effects' => [],
        'description' => '从天而降的箭雨',
    ],
    [
        'name' => '暗影步',
        'type' => 'active',
        'class_restriction' => 'ranger',
        'mana_cost' => 25,
        'cooldown' => 8,
        'effects' => [
            'backstab_bonus' => 1.5,
        ],
        'description' => '瞬间移动到敌人身后',
    ],
    [
        'name' => '治疗术',
        'type' => 'active',
        'class_restriction' => 'all',
        'mana_cost' => 20,
        'cooldown' => 8,
        'effects' => [
            'heal' => true,
        ],
        'description' => '恢复生命值',
    ],
    [
        'name' => '力量强化',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'strength_bonus' => 2,
        ],
        'description' => '被动提升力量',
    ],
    [
        'name' => '敏捷强化',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'dexterity_bonus' => 2,
        ],
        'description' => '被动提升敏捷',
    ],
    [
        'name' => '体力强化',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'vitality_bonus' => 2,
        ],
        'description' => '被动提升体力',
    ],
    [
        'name' => '能量强化',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'energy_bonus' => 2,
        ],
        'description' => '被动提升能量',
    ],
    [
        'name' => '吸血',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'life_steal' => 0.05,
        ],
        'description' => '攻击时回复生命值',
    ],
    [
        'name' => '回蓝',
        'type' => 'passive',
        'class_restriction' => 'all',
        'mana_cost' => 0,
        'cooldown' => 0,
        'effects' => [
            'mana_regen' => 2,
        ],
        'description' => '被动手动回复法力值',
    ],
];
