<?php

// 由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    ['id' => 40, 'name' => '布帽', 'type' => 'helmet', 'sub_type' => 'cloth', 'base_stats' => ['max_hp' => 10, 'defense' => 2], 'required_level' => 1, 'sockets' => 0, 'asset_key' => 'cloth-cap-helmet', 'icon_prompt' => 'RPG item icon, cloth cap helmet, fabric cap, simple stitching, detailed game item, soft shading, square, transparent background'],
    ['id' => 41, 'name' => '皮帽', 'type' => 'helmet', 'sub_type' => 'leather', 'base_stats' => ['max_hp' => 20, 'defense' => 5], 'required_level' => 5, 'sockets' => 0, 'asset_key' => 'leather-cap-helmet', 'icon_prompt' => 'RPG item icon, leather cap helmet, leather helmet, straps, detailed game item, soft shading, square, transparent background'],
    ['id' => 42, 'name' => '铁盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 50, 'defense' => 15], 'required_level' => 10, 'sockets' => 0, 'asset_key' => 'iron-helmet', 'icon_prompt' => 'RPG item icon, iron helmet, iron helm, metal texture, visor, detailed game item, soft shading, square, transparent background'],
    ['id' => 43, 'name' => '秘银头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 80, 'defense' => 5], 'required_level' => 15, 'sockets' => 0, 'asset_key' => 'mithril-helmet', 'icon_prompt' => 'RPG item icon, mithril helmet, mithril metal, silvery sheen, detailed game item, soft shading, square, transparent background'],
    ['id' => 44, 'name' => '龙骨头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 150, 'defense' => 40], 'required_level' => 20, 'sockets' => 0, 'asset_key' => 'dragon-bone-helmet', 'icon_prompt' => 'RPG item icon, dragon bone helmet, dragon bone, horn motif, detailed game item, soft shading, square, transparent background'],
    ['id' => 45, 'name' => '神圣头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 250, 'defense' => 60, 'max_mana' => 50], 'required_level' => 25, 'sockets' => 0, 'asset_key' => 'holy-helmet', 'icon_prompt' => 'RPG item icon, holy helmet, holy symbol, divine light, detailed game item, soft shading, square, transparent background'],
    ['id' => 46, 'name' => '圣骑士头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 400, 'defense' => 90, 'vitality' => 20], 'required_level' => 35, 'sockets' => 0, 'asset_key' => 'paladin-helmet', 'icon_prompt' => 'RPG item icon, paladin helmet, paladin design, cross or crown, detailed game item, soft shading, square, transparent background'],
    ['id' => 47, 'name' => '天使头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 600, 'defense' => 130, 'all_stats' => 10], 'required_level' => 45, 'sockets' => 0, 'asset_key' => 'angel-helmet', 'icon_prompt' => 'RPG item icon, angel helmet, angel wing motif, white gold, detailed game item, soft shading, square, transparent background'],
    ['id' => 48, 'name' => '神之头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 900, 'defense' => 180, 'vitality' => 40], 'required_level' => 55, 'sockets' => 0, 'asset_key' => 'divine-helmet', 'icon_prompt' => 'RPG item icon, divine helmet, divine radiance, ornate design, detailed game item, soft shading, square, transparent background'],
    ['id' => 49, 'name' => '永恒头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 1300, 'defense' => 250, 'all_stats' => 20], 'required_level' => 65, 'sockets' => 0, 'asset_key' => 'eternal-helmet', 'icon_prompt' => 'RPG item icon, eternal helmet, eternal metal, timeless aura, detailed game item, soft shading, square, transparent background'],
    ['id' => 50, 'name' => '混沌头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 2000, 'defense' => 350, 'vitality' => 60], 'required_level' => 75, 'sockets' => 0, 'asset_key' => 'chaos-helmet', 'icon_prompt' => 'RPG item icon, chaos helmet, chaos spikes, dark energy, detailed game item, soft shading, square, transparent background'],
    ['id' => 51, 'name' => '创世头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 3000, 'defense' => 480, 'all_stats' => 35], 'required_level' => 85, 'sockets' => 0, 'asset_key' => 'creation-helmet', 'icon_prompt' => 'RPG item icon, creation helmet, creation tier, powerful aura, detailed game item, soft shading, square, transparent background'],
    ['id' => 52, 'name' => '神王头盔', 'type' => 'helmet', 'sub_type' => 'plate', 'base_stats' => ['max_hp' => 4500, 'defense' => 650, 'vitality' => 100], 'required_level' => 95, 'sockets' => 0, 'asset_key' => 'god-king-helmet', 'icon_prompt' => 'RPG item icon, god king helmet, supreme crown helm, divine glory, detailed game item, soft shading, square, transparent background'],
];
