<?php

// 法师职业技能，由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '火球术',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 2,
        'skill_points_cost' => 1,
        'effects' => [],
        'description' => '发射火球，造成魔法伤害',
    ],
    [
        'name' => '冰霜新星',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 5,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '释放冰霜，造成范围伤害',
    ],
    [
        'name' => '魔力涌动',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'mana_bonus' => 20,
        ],
        'description' => '被动提升法力上限',
    ],
    [
        'name' => '雷击',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 25,
        'cooldown' => 4,
        'skill_points_cost' => 2,
        'effects' => [],
        'description' => '召唤闪电，瞬间造成高额伤害',
    ],
    [
        'name' => '魔法护盾',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 35,
        'cooldown' => 15,
        'skill_points_cost' => 2,
        'effects' => [
            'shield' => 100,
            'duration' => 8,
        ],
        'description' => '用法力值吸收伤害',
    ],
    [
        'name' => '奥术智慧',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 2,
        'effects' => [
            'spell_power_bonus' => 15,
        ],
        'description' => '被动提升魔法攻击力',
    ],
    [
        'name' => '陨石术',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 12,
        'skill_points_cost' => 4,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤陨石从天而降',
    ],
    [
        'name' => '法力燃烧',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 6,
        'skill_points_cost' => 2,
        'effects' => [
            'mana_burn' => 50,
        ],
        'description' => '燃烧敌人法力并造成伤害',
    ],
];
