<?php

// 法师职业技能，由 php artisan game:export-seeder-definitions 从数据库导出，供 GameSeeder 使用
return [
    [
        'name' => '火球术',
        'effect_key' => 'fireball',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 2,
        'skill_points_cost' => 1,
        'effects' => [],
        'description' => '发射火球，造成魔法伤害',
    ],
    [
        'name' => '冰箭',
        'effect_key' => 'ice-arrow',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 5,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [],
        'description' => '发射冰箭造成100%魔法伤害',
    ],
    [
        'name' => '燃烧',
        'effect_key' => 'fireball',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 5,
        'skill_points_cost' => 1,
        'effects' => [
            'dot' => 80,
            'dot_duration' => 5,
        ],
        'description' => '使敌人燃烧，每秒造成额外伤害',
    ],
    [
        'name' => '烈焰风暴',
        'effect_key' => 'meteor-storm',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 50,
        'cooldown' => 15,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤火焰风暴攻击所有敌人',
    ],
    [
        'name' => '冰霜新星',
        'effect_key' => 'ice-arrow',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 5,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '释放冰霜，造成范围伤害',
    ],
    [
        'name' => '冰封千里',
        'effect_key' => 'ice-arrow',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 20,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '冰冻所有敌人并造成大量伤害',
    ],
    [
        'name' => '魔力涌动',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 1,
        'effects' => [
            'mana_bonus' => 20,
        ],
        'description' => '被动提升法力上限',
    ],
    [
        'name' => '雷击',
        'effect_key' => 'lightning',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 25,
        'cooldown' => 4,
        'skill_points_cost' => 2,
        'effects' => [],
        'description' => '召唤闪电，瞬间造成高额伤害',
    ],
    [
        'name' => '连锁闪电',
        'effect_key' => 'lightning',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 20,
        'cooldown' => 6,
        'skill_points_cost' => 1,
        'effects' => [],
        'target_type' => 'all',
        'description' => '闪电在敌人之间弹跳',
    ],
    [
        'name' => '雷霆万钧',
        'effect_key' => 'lightning',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 18,
        'skill_points_cost' => 2,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤巨型雷电攻击所有敌人',
    ],
    [
        'name' => '魔法护盾',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 35,
        'cooldown' => 15,
        'skill_points_cost' => 2,
        'effects' => [
            'shield' => 100,
            'duration' => 8,
        ],
        'description' => '用法力值吸收伤害',
    ],
    [
        'name' => '奥术智慧',
        'type' => 'passive',
        'class_restriction' => 'mage',
        'mana_cost' => 0,
        'cooldown' => 0,
        'skill_points_cost' => 2,
        'effects' => [
            'spell_power_bonus' => 15,
        ],
        'description' => '被动提升魔法攻击力',
    ],
    [
        'name' => '陨石术',
        'effect_key' => 'meteor',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 60,
        'cooldown' => 12,
        'skill_points_cost' => 4,
        'effects' => [],
        'target_type' => 'all',
        'description' => '召唤陨石从天而降',
    ],
    [
        'name' => '法力燃烧',
        'type' => 'active',
        'class_restriction' => 'mage',
        'mana_cost' => 15,
        'cooldown' => 6,
        'skill_points_cost' => 2,
        'effects' => [
            'mana_burn' => 50,
        ],
        'description' => '燃烧敌人法力并造成伤害',
    ],
];
